services:
  - type: web
    name: cepcco-backend
    env: php
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php -S 0.0.0.0:$PORT index.php"
    envVars:
      - key: ENV
        value: production
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
